Add support for containerd and Docker builds

diff --git a/rootfs-overlay/lib/zebrafish/setup-persistence b/rootfs-overlay/lib/zebrafish/setup-persistence
--- a/rootfs-overlay/lib/zebrafish/setup-persistence
+++ b/rootfs-overlay/lib/zebrafish/setup-persistence
@@ -19,6 +19,7 @@ ZEBRAFISH_ZPOOL_VAULT="$ZEBRAFISH_ZPOOL/vault"
 ZEBRAFISH_ZPOOL_VAULT_PERSISTENT="$ZEBRAFISH_ZPOOL_VAULT/persistent"
 ZEBRAFISH_ZPOOL_OCI="$ZEBRAFISH_ZPOOL_VAULT/oci"
 ZEBRAFISH_ZPOOL_CONTAINERD="$ZEBRAFISH_ZPOOL_OCI/containerd"
+ZEBRAFISH_ZPOOL_DOCKER="$ZEBRAFISH_ZPOOL_OCI/docker"
 
 ZEBRAFISH_ZPOOL_COMPOSE="$ZEBRAFISH_ZPOOL_VAULT_PERSISTENT/compose"
 ZEBRAFISH_ZPOOL_DATA="$ZEBRAFISH_ZPOOL_VAULT_PERSISTENT/data"
@@ -34,6 +35,7 @@ ZEBRAFISH_LOG_DIR="/logs"
 ZEBRAFISH_OVERLAY_DIR="/overlay"
 ZEBRAFISH_OCI_DIR="/oci"
 ZEBRAFISH_CONTAINERD_DATA_DIR="$ZEBRAFISH_OCI_DIR/containerd"
+ZEBRAFISH_DOCKER_DATA_DIR="$ZEBRAFISH_OCI_DIR/docker"
 
 ZEBRAFISH_PERSISTENCE_MAGIC_HEADER="zebrafish-please-format-me"
 ZEBRAFISH_BIND_OVERLAY_MOUNT_DIR="/run/zebrafish/overlay"
@@ -120,6 +122,10 @@ create_zebrafish_datasets() {
 
     if [[ $datasets != *"$ZEBRAFISH_ZPOOL_CONTAINERD"* ]]; then
         zfs create -o compression=zstd -o mountpoint="$ZEBRAFISH_CONTAINERD_DATA_DIR" "$ZEBRAFISH_ZPOOL_CONTAINERD" || fail "Cannot create containerd dataset"
+    fi
+
+    if [[ $datasets != *"$ZEBRAFISH_ZPOOL_DOCKER"* ]]; then
+        zfs create -o compression=zstd -o mountpoint="$ZEBRAFISH_DOCKER_DATA_DIR" "$ZEBRAFISH_ZPOOL_DOCKER" || fail "Cannot create docker dataset"
     fi
 
     if [[ $datasets != *"$ZEBRAFISH_ZPOOL_COMPOSE"* ]]; then
@@ -253,6 +259,7 @@ overlay_zebrafish_data_dirs () {
 
 create_missing_directories() {
     mkdir -p "$ZEBRAFISH_CONTAINERD_DATA_DIR/io.containerd.snapshotter.v1.zfs" || fail "Failed to make containerd snapshotter directory"
+    mkdir -p "$ZEBRAFISH_DOCKER_DATA_DIR" || fail "Failed to make docker data directory"
     mkdir -p /logs/system || fail "Failed to make log directory"
 }
 
diff --git a/rootfs-overlay/lib/zebrafish/upgrade b/rootfs-overlay/lib/zebrafish/upgrade
--- a/rootfs-overlay/lib/zebrafish/upgrade
+++ b/rootfs-overlay/lib/zebrafish/upgrade
@@ -2,6 +2,15 @@
 set -e
 set -u
 
+# Read the OS release file
+if [[ -f /etc/os-release ]]; then
+    source /etc/os-release
+    ZEBRAFISH_VARIANT="${ZEBRAFISH_VARIANT:-containerd}"
+else
+    echo "/etc/os-release not found!"
+    exit 1
+fi
+
 CDN_HOSTNAME="https://cdn.zebrafish.tohka.us"
 
 # Check permissions
@@ -61,10 +70,10 @@ if [[ -z "$ACTUAL_DIR" ]]; then
 fi
 
 # Read the manifest
-EFI_RELEASE="$ACTUAL_DIR/$ZF_ARCH"
+EFI_RELEASE="$ACTUAL_DIR/$ZF_ARCH-$ZEBRAFISH_VARIANT"
 EFI_MANIFEST="$EFI_RELEASE.json"
 
-CDN_RELEASE="$CDN_HOSTNAME/$ZF_ARCH"
+CDN_RELEASE="$CDN_HOSTNAME/$ZF_ARCH-$ZEBRAFISH_VARIANT"
 CDN_MANIFEST="$CDN_RELEASE.json"
 CDN_ARCHIVE="$CDN_RELEASE.tar"
 
