fix unbound and remove nerdctl partitions

diff --git a/rootfs-overlay/etc/init.d/S42unbound b/rootfs-overlay/etc/init.d/S42unbound
--- a/rootfs-overlay/etc/init.d/S42unbound
+++ b/rootfs-overlay/etc/init.d/S42unbound
@@ -1,21 +1,25 @@
 #!/bin/sh
 
-NAME="unbound"
+NAME=unbound
 PIDFILE=/var/run/$NAME.pid
 LOGFILE=/logs/system/$NAME.log
 
-DAEMON_ARGS=""
+DAEMON_ARGS="-d -p"
 
 [ -r "/etc/default/$NAME" ] && . "/etc/default/$NAME"
 
 start() {
-	printf 'Starting %s: ' "$NAME"
-	$NAME && echo "OK" || echo "FAIL"
+	echo -n "Starting $NAME: "
+	start-stop-daemon --start --quiet --background \
+		--make-pidfile --pidfile $PIDFILE \
+		--startas /bin/sh -- -c "exec stdbuf -oL -eL $NAME $DAEMON_ARGS >> $LOGFILE 2>&1" \
+		&& echo "OK" || echo "FAIL"
 }
 
 stop() {
-	printf 'Stopping %s: ' "$DAEMON"
-	killall $NAME
+	echo -n "Stopping $NAME: "
+	start-stop-daemon --stop --quiet --pidfile $PIDFILE \
+		&& echo "OK" || echo "FAIL"
 }
 
 restart() {
