Add docker volume ZFS

diff --git a/rootfs-overlay/etc/init.d/S62dockerd b/rootfs-overlay/etc/init.d/S62dockerd
--- a/rootfs-overlay/etc/init.d/S62dockerd
+++ b/rootfs-overlay/etc/init.d/S62dockerd
@@ -1,4 +1,5 @@
 #!/bin/sh
+set -u
 
 . /lib/zebrafish/functions
 
@@ -11,7 +12,64 @@ DAEMON_ARGS="--data-root /oci/docker"
 
 [ -r /etc/default/$NAME ] && . /etc/default/$NAME $1
 
+create_symlink_safely() {
+	source="$1"
+	target="$2"
+
+	if [ -L "$source" ]; then
+		# If this is a symlink...
+		if [ "$(readlink -f "$source")" != "$target" ]; then
+			# And the symlink points to a different target...
+			# then remove the symlink and create a new one.
+			echo "Updating symlink: $source -> $target"
+			rm -f "$source"
+			ln -sf "$target" "$source"
+		else
+			# If the symlink already points to the correct target, do nothing.
+			return
+		fi
+	elif [ -d "$source" ]; then
+		# If this is a directory...
+		if [ "$(ls -A "$source")" ]; then
+			# And it is not empty...
+			# then we cannot create a symlink.
+			echo "Error: $source is a non-empty directory."
+			exit 1
+		else
+			# If it is empty, remove it and create a symlink.
+			echo "Removing empty directory: $source"
+			echo "Creating symlink: $source -> $target"
+			rm -rf "$source"
+			ln -sf "$target" "$source"
+		fi
+	elif [ -f "$source" ]; then
+		# If this is a file...
+		# Remove the file and create a symlink.
+		echo "Removing file: $source"
+		echo "Creating symlink: $source -> $target"
+		rm -f "$source"
+		ln -sf "$target" "$source"
+	else
+		# If it does not exist, create a symlink.
+		# First, ensure the parent directory exists.
+		parent_dir=$(dirname "$source")
+
+		if [ ! -d "$parent_dir" ]; then
+			echo "Creating parent directory: $parent_dir"
+			mkdir -p "$parent_dir"
+		fi
+
+		# Then create the symlink.
+		echo "Creating symlink: $source -> $target"
+		ln -sf "$target" "$source"
+	fi
+}
+
 do_start() {
+	# Ensure symlinks
+	create_symlink_safely /var/lib/docker /oci/docker
+	create_symlink_safely /oci/docker/volumes /volumes
+
     echo -n "Starting $NAME: "
 	start-stop-daemon --start --quiet --background \
 		--make-pidfile --pidfile "$PIDFILE" \
diff --git a/rootfs-overlay/lib/zebrafish/setup-persistence b/rootfs-overlay/lib/zebrafish/setup-persistence
--- a/rootfs-overlay/lib/zebrafish/setup-persistence
+++ b/rootfs-overlay/lib/zebrafish/setup-persistence
@@ -23,6 +23,7 @@ ZEBRAFISH_ZPOOL_DOCKER="$ZEBRAFISH_ZPOOL_OCI/docker"
 
 ZEBRAFISH_ZPOOL_COMPOSE="$ZEBRAFISH_ZPOOL_VAULT_PERSISTENT/compose"
 ZEBRAFISH_ZPOOL_DATA="$ZEBRAFISH_ZPOOL_VAULT_PERSISTENT/data"
+ZEBRAFISH_ZPOOL_VOLUMES="$ZEBRAFISH_ZPOOL_VAULT_PERSISTENT/volumes"
 ZEBRAFISH_ZPOOL_OVERLAY="$ZEBRAFISH_ZPOOL_VAULT_PERSISTENT/overlay"
 ZEBRAFISH_ZPOOL_LOGS="$ZEBRAFISH_ZPOOL_VAULT_PERSISTENT/logs"
 
@@ -34,6 +35,7 @@ ZEBRAFISH_VOL_DIR="/vol"
 ZEBRAFISH_LOG_DIR="/logs"
 ZEBRAFISH_OVERLAY_DIR="/overlay"
 ZEBRAFISH_OCI_DIR="/oci"
+ZEBRAFISH_VOLUMES_DIR="/volumes"
 ZEBRAFISH_CONTAINERD_DATA_DIR="$ZEBRAFISH_OCI_DIR/containerd"
 ZEBRAFISH_DOCKER_DATA_DIR="$ZEBRAFISH_OCI_DIR/docker"
 
@@ -117,31 +119,35 @@ create_zebrafish_datasets() {
     fi
 
     if [[ $datasets != *"$ZEBRAFISH_ZPOOL_OCI"* ]]; then
-        zfs create -o compression=zstd "$ZEBRAFISH_ZPOOL_OCI" || fail "Cannot create oci dataset"
+        zfs create -o compression=zstd -o sync=always "$ZEBRAFISH_ZPOOL_OCI" || fail "Cannot create oci dataset"
     fi
 
     if [[ $datasets != *"$ZEBRAFISH_ZPOOL_CONTAINERD"* ]]; then
-        zfs create -o compression=zstd -o mountpoint="$ZEBRAFISH_CONTAINERD_DATA_DIR" "$ZEBRAFISH_ZPOOL_CONTAINERD" || fail "Cannot create containerd dataset"
+        zfs create -o compression=zstd -o sync=always -o mountpoint="$ZEBRAFISH_CONTAINERD_DATA_DIR" "$ZEBRAFISH_ZPOOL_CONTAINERD" || fail "Cannot create containerd dataset"
     fi
 
     if [[ $datasets != *"$ZEBRAFISH_ZPOOL_DOCKER"* ]]; then
-        zfs create -o compression=zstd -o mountpoint="$ZEBRAFISH_DOCKER_DATA_DIR" "$ZEBRAFISH_ZPOOL_DOCKER" || fail "Cannot create docker dataset"
+        zfs create -o compression=zstd -o sync=always -o mountpoint="$ZEBRAFISH_DOCKER_DATA_DIR" "$ZEBRAFISH_ZPOOL_DOCKER" || fail "Cannot create docker dataset"
     fi
 
     if [[ $datasets != *"$ZEBRAFISH_ZPOOL_COMPOSE"* ]]; then
-        zfs create -o zebrafi.sh:persistent=true -o compression=zstd -o mountpoint="$ZEBRAFISH_COMPOSE_DIR" "$ZEBRAFISH_ZPOOL_COMPOSE" || fail "Cannot create compose dataset"
+        zfs create -o zebrafi.sh:persistent=true -o compression=zstd -o sync=always -o mountpoint="$ZEBRAFISH_COMPOSE_DIR" "$ZEBRAFISH_ZPOOL_COMPOSE" || fail "Cannot create compose dataset"
     fi
 
     if [[ $datasets != *"$ZEBRAFISH_ZPOOL_DATA"* ]]; then
-        zfs create -o zebrafi.sh:persistent=true -o compression=zstd -o mountpoint="$ZEBRAFISH_VOL_DIR" "$ZEBRAFISH_ZPOOL_DATA" || fail "Cannot create volume dataset"
+        zfs create -o zebrafi.sh:persistent=true -o compression=zstd -o sync=always -o mountpoint="$ZEBRAFISH_VOL_DIR" "$ZEBRAFISH_ZPOOL_DATA" || fail "Cannot create data dataset"
     fi
 
     if [[ $datasets != *"$ZEBRAFISH_ZPOOL_OVERLAY"* ]]; then
-        zfs create -o zebrafi.sh:persistent=true -o compression=zstd -o mountpoint="$ZEBRAFISH_OVERLAY_DIR" "$ZEBRAFISH_ZPOOL_OVERLAY" || fail "Cannot create overlay dataset"
+        zfs create -o zebrafi.sh:persistent=true -o compression=zstd -o sync=always -o mountpoint="$ZEBRAFISH_OVERLAY_DIR" "$ZEBRAFISH_ZPOOL_OVERLAY" || fail "Cannot create overlay dataset"
     fi
 
     if [[ $datasets != *"$ZEBRAFISH_ZPOOL_LOGS"* ]]; then
-        zfs create -o zebrafi.sh:persistent=true -o compression=zstd -o mountpoint="$ZEBRAFISH_LOG_DIR" "$ZEBRAFISH_ZPOOL_LOGS" || fail "Cannot create log dataset"
+        zfs create -o zebrafi.sh:persistent=true -o compression=zstd -o sync=always -o mountpoint="$ZEBRAFISH_LOG_DIR" "$ZEBRAFISH_ZPOOL_LOGS" || fail "Cannot create log dataset"
+    fi
+
+    if [[ $datasets != *"$ZEBRAFISH_ZPOOL_VOLUMES"* ]]; then
+        zfs create -o zebrafi.sh:persistent=true -o compression=zstd -o sync=always -o mountpoint="$ZEBRAFISH_VOLUMES_DIR" "$ZEBRAFISH_ZPOOL_VOLUMES" || fail "Cannot create volumes dataset"
     fi
 
     if [[ $datasets != *"$ZEBRAFISH_ZPOOL_SWAP"* ]]; then
@@ -259,7 +265,6 @@ overlay_zebrafish_data_dirs () {
 
 create_missing_directories() {
     mkdir -p "$ZEBRAFISH_CONTAINERD_DATA_DIR/io.containerd.snapshotter.v1.zfs" || fail "Failed to make containerd snapshotter directory"
-    mkdir -p "$ZEBRAFISH_DOCKER_DATA_DIR" || fail "Failed to make docker data directory"
     mkdir -p /logs/system || fail "Failed to make log directory"
 }
 
